# Generated by Django 4.2.15 on 2024-08-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=150)),
                ('mobile', models.PositiveIntegerField(null=True)),
                ('github', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('facebook', models.CharField(max_length=150)),
                ('twitter', models.CharField(max_length=150)),
                ('location', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
