# Generated by Django 4.2.15 on 2024-08-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_profile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=100)),
                ('level', models.PositiveIntegerField(max_length=3, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='profileapp.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
