# Generated by Django 4.2.15 on 2024-08-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_technologies_delete_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='file',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
