# Generated by Django 4.2.15 on 2024-08-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_technologies_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='level',
            field=models.TextField(max_length=3, null=True),
        ),
    ]
