# Generated by Django 4.2.15 on 2024-08-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='website_link',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
