# Generated by Django 4.2.15 on 2024-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_projects_website_link_alter_projects_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='website_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
