# Generated by Django 4.2.15 on 2024-08-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0012_alter_projects_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
