# Generated by Django 4.2.15 on 2024-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0014_alter_projects_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
