# Generated by Django 4.2.15 on 2024-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0015_alter_projects_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='file',
            field=models.CharField(max_length=22000, null=True),
        ),
    ]
