# Generated by Django 4.2.15 on 2024-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0019_alter_projects_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='file',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_file',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
