# Generated by Django 4.2.15 on 2024-08-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0020_remove_projects_file_projects_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_file',
        ),
        migrations.AddField(
            model_name='projects',
            name='file',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_link',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='website_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='technologies',
            name='file',
            field=models.TextField(max_length=15000, null=True),
        ),
    ]
