# Generated by Django 4.2.15 on 2024-08-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0021_remove_projects_project_file_projects_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='herofile',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
