# Generated by Django 4.2.15 on 2024-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0024_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='user',
        ),
        migrations.AddField(
            model_name='clients',
            name='seller_profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='clients', to='profileapp.profile'),
        ),
    ]
