# Generated by Django 4.2.15 on 2024-08-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0026_alter_clients_seller_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='rating',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='RATING[4]', null=True),
        ),
    ]
