# Generated by Django 4.2.15 on 2024-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0027_alter_clients_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
