# Generated by Django 4.2.15 on 2024-08-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0029_alter_clients_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='RATING[2]', max_length=1, null=True),
        ),
    ]
