# Generated by Django 4.2.15 on 2024-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0030_alter_clients_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='role',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
