# Generated by Django 4.2.15 on 2024-08-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0031_clients_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discipline',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
